[package]
name = "FactiorialS"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"
aws-config = "1.5.0"
aws-sdk-ses = "1.28.0"
aws_lambda_events = "0.15.1"
lambda_runtime = "0.13.0"
tokio = { version = "1", features = ["macros"] }
serde = "1.0.215"
serde_json = "1.0.133"
